language: cpp
sudo: required
compiler:
  - gcc
services:
  - docker
# Distro versions
env:
  global:
    - MAKEFLAGS="-j 2"
  matrix:
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu16.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu18.04 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=ubuntu18.10 CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=False"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=True"
    - BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=False"
    #- BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=True"
    #- BUILD_TARGET=arch CONFIGURE_FLAGS="-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=False"
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=True -DJNI=False'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=True -DTCP=False -DJNI=False'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=True -DJNI=False'
    #- BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=True'
    #- BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Release -DUDP=False -DTCP=False -DJNI=False'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=True -DJNI=False'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=True -DTCP=False -DJNI=False'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=True'
    - BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=True -DJNI=False'
    #- BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=True'
    #- BUILD_TARGET=alpine CONFIGURE_FLAGS='-DCMAKE_BUILD_TYPE=Debug -DUDP=False -DTCP=False -DJNI=False'

script:
  - docker run -e MAKEFLAGS="$MAKEFLAGS" -v $(pwd):/build augugrumi/astaire-dockerbuilds:$BUILD_TARGET $CONFIGURE_FLAGS
